### ISSUE TITLE
Remove workaround

### ISSUE THREAD

**Issue by ojongerius** [alphagov/paas-cf#1170]
Hi there,

I stumbled on this `FIXME` while doing a GH code search for usage of a library I work on: https://github.com/alphagov/paas-cf/blob/087995e459bd4b0959d9ac521b1d7c9903ea926a/concourse/pipelines/create-cloudfoundry.yml#L2251

As https://github.com/zorkian/go-datadog-api/issues/56 has been closed off for a while now,  you should be able to remove your work around when and if you see fit.

**Comment by camelpunch** [comment]
Thanks @ojongerius! We're putting this through our review grinder now.

**Comment by dcarley** [comment]
Merged in #1208. Thanks again!
