### ISSUE TITLE
Pre-requisites section does not incldue the shared-cf-blobstore bucket-<env>

### ISSUE THREAD

**Issue by jimconner** [alphagov/paas-cf#375]
The pre-requisites section of the documentation does not include details about the creation of the shared-cf-blosh-blobstore-<env> bucket(s). These buckets are not created by the paas-cf pipeline, so should be listed in the pre-requisites section.

Further to this, because S3 bucket names are globally unique, it is not possible for any other organisation outside of GDS to use the same bucket-name format, so it would be good to be able to parametrise the `shared-cf-bosh-blobstore-` part of the bucket name for different organisations to be able to use paas-cf without having to fork and change code.

**Comment by samcrang** [comment]
I _think_ this has already been resolved. Closing.
