### ISSUE TITLE
Bootstrap-concourse Vagrantfile contains hardcoded subnet and security-group IDs

### ISSUE THREAD

**Issue by jimconner** [alphagov/paas-cf#377]
The Vagrantfile contains hard-coded subnet and security group IDS which correspond to GDS's AWS account only. 

It would be really good to parametrise these settings (or at least document that these will need to change for deployment outside GDS)

**Comment by samcrang** [comment]
I'm closing this because it's been a long time since this was opened and it doesn't appear that we have `Vagrantfile`s in this repo anymore.
