### ISSUE TITLE
Hardcoded DNS names and Route53 Zone IDS in Makefile and TFVars

### ISSUE THREAD

**Issue by jimconner** [alphagov/paas-cf#378]
Because the terraform runs happen within the Concourse deployment pipeline(s), the use of hardcoded DNS names and Zone IDs within the TFVars makes it necessary to fork paas-cf and update pipelines to pull from the forked repo instead. 

It would be great for other organisations outside GDS to be able to deploy paas-cf without having to fork the codebase.

**Comment by samcrang** [comment]
I've not digged into this, but from reading this I don't think this is the case anymore. Also, it's probably a Nice To Have™ for people other the GDS to use this repo directly. Closing.
